name: Generate Snake Game
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: darshantate
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: output
